# Generated by Django 5.2.14 on 2026-05-17 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nim', models.CharField(max_length=20)),
                ('prodi', models.CharField(max_length=50)),
                ('semester', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PembayaranUKT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominal', models.IntegerField()),
                ('jumlah_bayar', models.IntegerField()),
                ('persentase', models.IntegerField()),
                ('status', models.CharField(max_length=30)),
                ('deadline', models.DateField()),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.mahasiswa')),
            ],
        ),
    ]
