# Generated by Django 5.2.14 on 2026-05-26 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pembayaranukt',
            name='persentase',
        ),
    ]
