# Generated by Django 5.2.14 on 2026-05-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_pembayaranukt_persentase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembayaranukt',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
