# Generated by Django 5.2.14 on 2026-05-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_pembayaranukt_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembayaranukt',
            name='persentase',
            field=models.IntegerField(default=0),
        ),
    ]
