# Generated by Django 5.2.14 on 2026-05-30 16:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_pembayaranukt_persentase'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswa',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pembayaranukt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pembayaranukt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
